mode = "fast"

[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	tnt = "fast"
	creeper = "fast"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				allay = true
				axolotl = true
				bee = true
				area_effect_cloud = true
				bat = true
				arrow = true
				armor_stand = true
				player = true

