name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "063ddefff910807040d184df8c385c4142b32522903a65de8cbf026fa18e52b6"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
