name = "Fabulously Optimized"
version = "3.0.0-alpha.2b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "307a6e5ec355fe84fc2c12c08e453968d3211d162560796bf78b28fdbb145ccf"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
