name = "Fabulously Optimized"
version = "3.0.0-alpha.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b870fa7f6a4889c4d767792c4f3a19dcf2945721be786ae7724c7f89eb22b5"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
