name = "Fabulously Optimized"
version = "3.0.0-alpha.2c"
pack-format = "packwiz:1.0.0"
version = "3.0.0-alpha.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ca2212c93368a9c788cc3ee0eb25e5699eab0f40aada76d57397af4e315218"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
