name = "Fabulously Optimized"
version = "3.0.0-alpha.2a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "985e45b5fca04a7e931159f2dcf20799ff677cac5a4bd223b796a188044381a7"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
