name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "188faf66dfe1e942442eabcda666222aabc1bae11780901ec78cba323e7d7627"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
