name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60ea9f9ce29c99d459f4543ed350baf0d18492667377d29b69079b43cc0bd749"

[versions]
fabric = "0.12.4"
minecraft = "1.17.1"
