name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7030a1a4f091e4235ec0c32c79fb342c1fed6d495f9cc5343f8485b0e8d38fd8"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
