name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b5f6c1f7aa25eb9e9ca47a62a0ee8b8ad4144e238f6dbc0bf4f5585390a53fa"

[versions]
fabric = "0.12.11"
minecraft = "1.17.1"
