name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc02c96d47ab1b73b4333c83632cf2077e79cdcaeb224fcefac7c2d5d58a551"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
