name = "Fabulously Optimized"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1f32be5139669cca2e07f17477ac35e938b5c8eadbd3f7afb03eb6bd352ec3f"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
