name = "Fabulously Optimized"
version = "3.1.0-alpha.1b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf096e634617cc9d9a9b18e440634279e7540b86ab6689a8bf61235407dac0b9"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
