name = "Fabulously Optimized"
version = "4.0.0-beta.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43db787c7f4d91f73d71190f90eab3f86af6b94931c572a54a6791f6ee82f242"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
