name = "PepegaSanctuary"
version = "4.0.0-beta.11-2.2-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f514d2e04ca4e6bec477ff30879a9ced802951a03ca6042f7ae400797295ae7"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
