name = "PepegaSanctuary"
version = "4.0.0-beta.11-2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6e948bc6d85f3c735a5eaecf90c8ebdba0ccfff18c8a00add55d8ad2f7f8b4c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
