name = "Fabulously Optimized"
version = "3.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83acfd6a7fc90f498aa09268d7c6051d1519c28dba5e21c95f20d1e1193de529"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
